POST http://localhost:7071/api/InitBlobUpload HTTP/1.1
Content-Type: application/json

{
        "PathToArchive": "c:\\labs\\uploadblobs-data",
        "InstanceId": "gbelenky-print-bud"
}

###

GET http://localhost:7071/api/GetStatus HTTP/1.1
